CREATE TABLE `suppliers` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `corporate_name` varchar(255) NOT NULL,
  `CNPJ` varchar(14) NOT NULL,
  `city` int(11) NOT NULL,
  `state` int(11) NOT NULL,
  `street` varchar(255) NOT NULL,
  `neighborhood` varchar(255) NOT NULL,
  `certificate` tinyint(1) NOT NULL,
  `email` varchar(255) DEFAULT NULL,
  `state_registration` varchar(9) NOT NULL,
  `register_data` date DEFAULT NULL,
  `fical_classification` varchar(255) DEFAULT NULL,
  `material_certificate` tinyint(1) DEFAULT NULL,
  `justificative` varchar(350) DEFAULT NULL,
  `phone` varchar(10) DEFAULT NULL,
  `cep` varchar(8) DEFAULT NULL,
  `expireCertificationDate` date DEFAULT NULL,
  `contact` varchar(100) DEFAULT NULL,
  `contactphone` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `city` (`city`),
  KEY `state` (`state`),
  CONSTRAINT `suppliers_ibfk_1` FOREIGN KEY (`city`) REFERENCES `city` (`id`),
  CONSTRAINT `suppliers_ibfk_2` FOREIGN KEY (`state`) REFERENCES `state` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=latin1;
