CREATE TABLE `bank` (
  `id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `bank` varchar(250) NOT NULL,
  `febraban_code` varchar(10) NOT NULL
);

INSERT INTO `bank` (`bank`, `febraban_code`)
VALUES
('Banco ABC Brasil S.A.', '246'),
('Banco ABN AMRO Real S.A.', '356'),
('Banco Alfa S.A.', '025'),
('Banco Alvorada S.A.', '641'),
('Banco Banerj S.A.', '029'),
('Banco Banestado S.A.', '038'),
('Banco Barclays S.A.', '740'),
('Banco BBM S.A.', '107'),
('Banco Beg S.A.', '031'),
('Banco Bem S.A.', '036'),
('Banco BM&F de Serviços de Liquidação e Custódia S.A', '096'),
('Banco BMC S.A.', '394'),
('Banco BMG S.A.', '318'),
('Banco BNP Paribas Brasil S.A.', '752'),
('Banco Boavista Interatlântico S.A.', '248'),
('Banco Bradesco S.A.', '237'),
('Banco Brascan S.A.', '225'),
('Banco Cacique S.A.', '263'),
('Banco Calyon Brasil S.A.', '222'),
('Banco Cargill S.A.', '040'),
('Banco Citibank S.A.', '745'),
('Banco Comercial e de Investimento Sudameris S.A.', '215'),
('Banco Cooperativo do Brasil S.A. – BANCOOB', '756'),
('Banco Cooperativo Sicredi S.A. – BANSICREDI', '748'),
('Banco Credit Suisse (Brasil) S.A.', '505'),
('Banco Cruzeiro do Sul S.A.', '229'),
('Banco da Amazônia S.A.', '003'),
('Banco Daycoval S.A.', '707'),
('Banco de Pernambuco S.A. – BANDEPE', '024'),
('Banco de Tokyo-Mitsubishi UFJ Brasil S.A.', '456'),
('Banco Dibens S.A.', '214'),
('Banco do Brasil S.A.', '001'),
('Banco do Estado de Santa Catarina S.A.', '027'),
('Banco do Estado de Sergipe S.A.', '047'),
('Banco do Estado do Pará S.A.', '037'),
('Banco do Estado do Rio Grande do Sul S.A.', '041'),
('Banco do Nordeste do Brasil S.A.', '004'),
('Banco Fator S.A.', '265'),
('Banco Fibra S.A.', '224'),
('Banco Finasa S.A.', '175'),
('Banco Fininvest S.A.', '252'),
('Banco GE Capital S.A.', '233'),
('Banco Gerdau S.A.', '734'),
('Banco Guanabara S.A.', '612'),
('Banco Ibi S.A. Banco Múltiplo', '063'),
('Banco Industrial do Brasil S.A.', '604'),
('Banco Industrial e Comercial S.A.', '320'),
('Banco Indusval S.A.', '653'),
('Banco Intercap S.A.', '630'),
('Banco Investcred Unibanco S.A.', '249'),
('Banco Itaú BBA S.A.', '184-8'),
('Banco Itaú Holding Financeira S.A.', '652'),
('Banco Itaú S.A.', '341'),
('Banco ItaúBank S.A', '479'),
('Banco J. P. Morgan S.A.', '376'),
('Banco J. Safra S.A.', '074'),
('Banco Luso Brasileiro S.A.', '600'),
('Banco Mercantil de São Paulo S.A.', '392'),
('Banco Mercantil do Brasil S.A.', '389'),
('Banco Merrill Lynch de Investimentos S.A.', '755'),
('Banco Nossa Caixa S.A.', '151'),
('Banco Opportunity S.A.', '045'),
('Banco Panamericano S.A.', '623'),
('Banco Paulista S.A.', '611'),
('Banco Pine S.A.', '643'),
('Banco Prosper S.A.', '638'),
('Banco Rabobank International Brasil S.A.', '747'),
('Banco Rendimento S.A.', '633'),
('Banco Rural Mais S.A.', '072'),
('Banco Rural S.A.', '453'),
('Banco Safra S.A.', '422'),
('Banco Santander Banespa S.A.', '008'),
('Banco Schahin S.A.', '250'),
('Banco Simples S.A.', '749'),
('Banco Société Générale Brasil S.A.', '366'),
('Banco Sofisa S.A.', '637'),
('Banco Sudameris Brasil S.A.', '347'),
('Banco Sumitomo Mitsui Brasileiro S.A.', '464'),
('Banco Triângulo S.A.', '634'),
('Banco UBS Pactual S.A.', '208'),
('Banco UBS S.A.', '247'),
('Banco Único S.A.', '116'),
('Banco Votorantim S.A.', '655'),
('Banco VR S.A.', '610'),
('Banco WestLB do Brasil S.A.', '370'),
('BANESTES S.A. Banco do Estado do Espírito Santo', '021'),
('Banif-Banco Internacional do Funchal (Brasil)S.A.', '719'),
('Bankpar Banco Multiplo S.A.', '204'),
('BB Banco Popular do Brasil S.A.', '073-6'),
('BPN Brasil Banco Mútiplo S.A.', '069-8'),
('BRB – Banco de Brasília S.A.', '070'),
('Caixa Econômica Federal', '104'),
('Citibank N.A.', '477'),
('Deutsche Bank S.A. – Banco Alemão', '487'),
('Dresdner Bank Brasil S.A. – Banco Múltiplo', '751'),
('Dresdner Bank Lateinamerika Aktiengesellschaft', '210'),
('Hipercard Banco Múltiplo S.A.', '062'),
('HSBC Bank Brasil S.A. – Banco Múltiplo', '399'),
('ING Bank N.V.', '492'),
('JPMorgan Chase Bank', '488'),
('Lemon Bank Banco Múltiplo S.A.', '065'),
('UNIBANCO – União de Bancos Brasileiros S.A.', '409'),
('Unicard Banco Múltiplo S.A.', '230');