CREATE TABLE IF NOT EXISTS service(

id INT(11) NOT NULL AUTO_INCREMENT,
name VARCHAR(255) NOT NULL,
meal double NOT NULL,
stay_price VARCHAR(255) NOT NULL,
price_I_I_I DOUBLE NOT NULL,
price_I_I_II DOUBLE NOT NULL,
price_I_II_I DOUBLE NOT NULL,
price_I_II_II DOUBLE NOT NULL,
price_I_III_I DOUBLE NOT NULL,
price_I_III_II DOUBLE NOT NULL,
price_II_I_I  DOUBLE NOT NULL,
price_II_I_II DOUBLE NOT NULL,
price_II_II_I DOUBLE NOT NULL,
price_II_II_II DOUBLE NOT NULL,
price_II_III_I DOUBLE NOT NULL,
price_II_III_II DOUBLE NOT NULL,
price_per_km DOUBLE NOT NULL,

PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS ptc(

id INT(11) NOT NULL AUTO_INCREMENT,
title VARCHAR(255),
client INT(11) NOT NULL,
brute_value DOUBLE NOT NULL,
brute_plus_aliquot  DOUBLE NOT NULL,
aliquot DOUBLE NOT NULL,
contribuition DOUBLE NOT NULL,
suggested DOUBLE NOT NULL,
discount DOUBLE NOT NULL,
final_value DOUBLE NOT NULL,

PRIMARY KEY(id),
FOREIGN KEY(client) REFERENCES client(id)
);

CREATE TABLE IF NOT EXISTS ptc_material(

id INT(11) NOT NULL AUTO_INCREMENT,
ptc INT(11) NOT NULL,
material INT(11) NOT NULL,
ammount INT(11) NOT NULL,
price DOUBLE,

PRIMARY KEY(id),
FOREIGN KEY(ptc) REFERENCES ptc(id),
FOREIGN KEY(material) REFERENCES product(id)

);

CREATE TABLE IF NOT EXISTS ptc_product(

id INT(11) NOT NULL AUTO_INCREMENT,
ptc INT(11) NOT NULL,
product INT(11) NOT NULL,
ammount INT(11) NOT NULL,
price DOUBLE,

PRIMARY KEY(id),
FOREIGN KEY(ptc) REFERENCES ptc(id),
FOREIGN KEY(product) REFERENCES compost_product(id)

);

CREATE TABLE IF NOT EXISTS ptc_kit(

id INT(11) NOT NULL AUTO_INCREMENT,
ptc INT(11) NOT NULL,
kit INT(11) NOT NULL,
ammount INT(11) NOT NULL,
price DOUBLE,

PRIMARY KEY(id),
FOREIGN KEY(ptc) REFERENCES ptc(id),
FOREIGN KEY(kit) REFERENCES kit(id)

);

CREATE TABLE IF NOT EXISTS ptc_service(

id INT(11) NOT NULL AUTO_INCREMENT,
ptc INT(11) NOT NULL,
service INT(11) NOT NULL,


PRIMARY KEY(id),
FOREIGN KEY(ptc) REFERENCES ptc(id),
FOREIGN KEY(service) REFERENCES service(id)

);
